---
title: "fa_analysis_stats_figs"
author: "Christine Vega"
date: "2026-04-28"
output: html_document
---

```{r clear workspace and set wd}
### clear work space 
  rm(list = ls())

### set working directory 
  setwd('/Users/christinevega/Desktop/UoAkron Postdoc/Fall Away Peg Board/R_fa_analysis/fa_analysis')
  
### load packages
  library(tidyr)
  library(dplyr)
  library(ggplot2)
  library(lme4)
  library(lmerTest)
  library(emmeans)
  library(pbkrtest)
  library(effectsize)

### import csv containing metadata and output variables from python
  data <- read.csv("2026-05-06_fa_metadata_output_variables.csv")

```

```{r reformat csv}

# need to reformat the imported csv from "wide" (1 row per trial, all variables as columns) to "long" (multiple rows per trial, each variable has its own row)

data_long <- pivot_longer(data, 
              cols = -c("date", "mocap_csv_name", "individual", "block_number",
              "trial", "grade"),
              names_to = c("time", "variable"), # create new column with header info
              names_pattern = "(pre|post)?_?(.*)", # optionally use pre/post
              values_to = "value") # holds data values

## output variable "avg_body_angle_spread" for all spatial chunks does not have a pre and post component. Convert blanks to NaN.
data_long$time[data_long$time == ""] <- NaN

```

```{r distribution of each variable's data}
## first, determine distribution of all output variables
  #1. speed
  ## isolate all pre avg speed values by grade
  pre_A <- data_long$value[
    data_long$variable == "avg_speed" &
    data_long$time == "pre" &
    data_long$grade == "A"]

  pre_B <- data_long$value[
    data_long$variable == "avg_speed" &
    data_long$time == "pre" &
    data_long$grade == "B"]
  
  ## create histogram plots and overlay kernel density line for each "grade
    # set up side by side plot area
      par(mfrow = c(1, 2))
    
    # plot pre avg speed for "grade A"
      hist(pre_A,
        prob = TRUE,
        col = "lightblue",
        main = "Grade A - Pre Speed",
        xlab = "Pre Avg Speed")

      lines(density(pre_A), col = "red", lwd = 2)
  
      # plot pre avg speed for "grade B"
        hist(pre_B,
          prob = TRUE,
          col = "lightgreen",
          main = "Grade B - Pre Speed",
          xlab = "Pre Avg Speed")

        lines(density(pre_B), col = "red", lwd = 2)
  
  ## now plot both distributions on the same histogram
    # align the histograms
      all_vals <- c(pre_A, pre_B)

      brks <- seq(min(all_vals), max(all_vals), length.out = 20)
      
    # plot with transparency so both distributions visible
      hist(pre_A,
        breaks = brks,
        probability = TRUE,
        col = rgb(1, 0, 0, 0.4),   # red transparent
        xlim = range(all_vals),
        main = "Pre Avg Speed: Grade A vs B",
        xlab = "Avg Speed")

      hist(pre_B,
        breaks = brks,
        probability = TRUE,
        col = rgb(0, 0, 1, 0.4),   # blue transparent
        add = TRUE)
      
      # pre speed data seems to fit gamma distribution because they are positive
      # (cannot be 0) and are skewed
      
  ## subset all speed (pre + post) data
    speed_all <- data_long$value[
    data_long$variable == "avg_speed"]
  
  ### set up plot area
      par(mfrow = c(1, 1))
    
    # plot avg speed 
      hist(speed_all,
        prob = TRUE,
        col = "lightblue",
        main = "Average Speed (Pre + Post)",
        xlab = "Avg Speed")

      lines(density(na.omit(speed_all)), col = "red", lwd = 2)
    
      # all speed seems to fit a gamma distribution because they are positive
      # (cannot be 0) and are skewed
      
  #2. area
  ## subset area data
    area_data <- data_long$value[
    data_long$variable %in% c("area_fa", "area_ahead1", "area_ahead2",
                             "area_ahead3","area_behind1","area_behind2",
                             "area_behind3")]
  
  ## make histogram
  hist(area_data,
        prob = TRUE,
        col = "lightblue",
        main = "Polygon Area Distribution",
        xlab = "Area")
    
    # area data seems to fit gamma distribution because they are positive
    # (cannot be 0) and are skewed
  
  #3. body angle spread
   ## subset area data
    spread_data <- data_long$value[
    data_long$variable %in% c("avg_body_angle_spread_fa",
                              "avg_body_angle_spread_ahead1", 
                              "avg_body_angle_spread_ahead2",
                              "avg_body_angle_spread_ahead3",
                              "avg_body_angle_spread_behind1",
                              "avg_body_angle_spread_behind2",
                              "avg_body_angle_spread_behind3")]
  
  ## make histogram
  hist(spread_data,
        prob = TRUE,
        col = "lightblue",
        main = "Body Angle Spread Distribution",
        xlab = "Angle Spread")
  
  # angle spread data seems to fit gamma distribution because they are positive
  # (cannot be 0) and are skewed
  
  #4. body angle
   ## subset body angle data
    body_angle_data <- data_long$value[
    data_long$variable %in% c("avg_body_angle_fa",
                              "avg_body_angle_ahead1", 
                              "avg_body_angle_ahead2",
                              "avg_body_angle_ahead3",
                              "avg_body_angle_behind1",
                              "avg_body_angle_behind2",
                              "avg_body_angle_behind3")]
  
  ## make histogram
  hist(body_angle_data,
        prob = TRUE,
        col = "lightblue",
        main = "Body Angle Distribution",
        xlab = "Angle (degrees)")
  
  # body angle data seems to have uniform distribution 
      
```      
```{r plot change in speed from pre to post}

## calculate the difference in speed (post_avg speed - pre_avg_speed)
  #subset speed data
  speed_data <- data_long[data_long$variable == "avg_speed",]

  #keep only rows with metadata and speed values
  speed_data <- speed_data[1:132, ]

  #split pre and post
  pre_speed <- speed_data[speed_data$time == "pre",]
  post_speed <- speed_data[speed_data$time == "post",]
  
  #use identifying variables to match up rows
  speed_change <- merge(pre_speed, post_speed,
                        by = c("date", "mocap_csv_name", "individual", "grade",
                        "block_number","trial"),
                        suffixes = c("_pre", "_post"))
  #calculate change in speed
  speed_change$delta_speed <- speed_change$value_post - speed_change$value_pre
  
## make histogram
  hist(speed_change$delta_speed,
        prob = TRUE,
        col = "lightblue",
        main = "Speed Change Distribution",
        xlab = "Speed Change")
  
  # speed change seems to be either normal distribution or maybe a right skew
  # (though cannot use gamma bc negative values OK)
  
## visualize change in speed from pre to post
  # put pre first
  speed_data$time <- factor(speed_data$time,
                          levels = c("pre", "post"))

  # summarize pre and post speed values by individual
  speed_plot <- speed_data %>%
    group_by(individual, time) %>%
    summarise(mean_speed = mean(value, na.rm = TRUE), .groups = "drop")

  # plot mean speeds for an individual with slopes between pre and post    
  ggplot(speed_plot, aes(x = time, y = mean_speed, group = individual)) +
  geom_line(color = "grey60", alpha = 0.6) +
  geom_point(size = 2) +
  
  stat_summary(aes(group = 1),
               fun = mean,
               geom = "line",
               linewidth = 1.5,
               color = "black") +
  
  stat_summary(aes(group = 1),
               fun = mean,
               geom = "point",
               size = 3,
               color = "black") +
  
  theme_classic()

  # on average, most individuals (n = 8/9) slow down after the perturbation
  
  
```
 
``` {r run models on speed}     

## make categorical variables factors
  data_long$variable <- factor(data_long$variable)
  data_long$time <- factor(data_long$time)
  data_long$grade <- factor(data_long$grade)
  data_long$individual <- factor(data_long$individual)

## does average pre speed differ between grade A and B?
  # run general linear model on pre speed + deal with repeated measures
    grade_model <- lmer(value ~ grade + (1 | individual), data = pre_speed)
    summary(grade_model)
      #lmer for gaussian mixed models
      #glmer for non gaussian mixed models
    
    # there is a significant difference between grade A and grade B trials
    # grade B significantly greater average speed than grade A 
      # not necessarily surprising and could do a model with speed as continuous
      # covariate to still pool? speed often differs between individuals when they
      # self select speed for behavioral trials
    
    # calculate Cohen's d to evaluate effect size (0.2 = small, 0.5 = medium, 0.8 = large)
      eff_size(emmeans(grade_model, ~ grade),
         sigma = sigma(grade_model),
         edf = df.residual(grade_model))
      # medium to large effect size of grade
    
    # get predicted values from model
    emm_grade <- emmeans(grade_model, ~ grade)
    emm_grade_df <- as.data.frame(emm_grade)

    # create plot
    ggplot(emm_grade_df, aes(x = grade, y = emmean, group = 1)) +
      geom_line(size = 1.2) +
      geom_point(size = 3) +
      geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL), width = 0.1) +
      labs(title = "Effect of Grade", y = "Estimated Mean Value") +
      theme_minimal()
    
## run a general linear mixed model on pre v post speed 
    time_model <- lmer(value ~ time + (1 | individual), data = speed_data)
    summary(time_model)
    
    # there is a significant decrease in speed after the perturbation
    # which is what we expected to occur 
    
     # calculate Cohen's d to evaluate effect size (0.2 = small, 0.5 = medium, 0.8 = large)
      eff_size(emmeans(time_model, ~ time),
         sigma = sigma(time_model),
         edf = df.residual(time_model))
      #small to medium effect size of time
    
    # get predicted values from model
    emm_time <- emmeans(time_model, ~ time)
    emm_time_df <- as.data.frame(emm_time)

    # create plot
    ggplot(emm_time_df, aes(x = time, y = emmean, group = 1)) +
      geom_line(size = 1.2) +
      geom_point(size = 3) +
      geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL), width = 0.1) +
      labs(title = "Effect of Time", y = "Estimated Mean Value") +
      theme_minimal()
    
## run a general linear mixed model on interaction between time and grade
    time_grade_int_model <- lmer(value ~ time * grade + (1 | individual), data =
                                   speed_data)
    summary(time_grade_int_model)
    
    # no significant difference so the speed change from pre to post does not
    # differ by grade (no effect of time); only significant is that grade b starts
    # higher which we know from the above grade_model (significant main effect of
    # grade)
    
      # calculate Cohen's d to evaluate effect size (0.2 = small, 0.5 = medium, 0.8 = large)
      eff_size(emmeans(time_grade_int_model, ~ time * grade),
         sigma = sigma(time_grade_int_model),
         edf = df.residual(time_grade_int_model))
        # grade a small to medium effect of decrease over time
        # grade b medium to large effect of decrease over time
        # not surprising given grade b has higher pre speed but time * grade interaction
        # did not show time effect, only grade
    
    # plot
      # make predicted values from model into data frame
      emm_time_grade <- emmeans(time_grade_int_model, ~ time * grade)
      emm_time_grade_df <- as.data.frame(emm_time_grade)
    
      # create plot
      ggplot(emm_time_grade_df, aes(x = time, y = emmean, color = grade, group = grade)) +
        geom_line(size = 1.2) +
        geom_point(size = 3) +
        geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL), width = 0.1) +
        labs(x = "Time", y = "Estimated Mean Value",
            title = "Time × Grade Interaction (Mixed Model)") +
        theme_minimal()

## check that distribution for models fits actual distribution of data for all current code      
            
## get AIC values
  # AIC(model_name)
  # create table for AIC values
# # table code from circ stats - need to modify for here
  
  # Create a table to hold the corresponding linear model output 
  #table_time_grade <- as.data.frame(emmeans_time_grade_df$contrasts, infer = TRUE)
  
  # Rename column names in table
  #colnames(table_time_grade) <- c("Comparison", "Estimate", "SE", "DF", "lower CI", "upper CI", "T_Value", "P_Value")
  
  # Create descriptive statistics table from the original data (not from the model)
  # These data correspond to the linear box plots in the paper
  #table_time_grade_linear_descriptives <- speed_data %>%
    #group_by(time*grade) %>%
    #summarise(
      #Mean = mean(R_tongue_protraction_min_CyclePercent, na.rm = TRUE),
      #SD = sd(R_tongue_protraction_min_CyclePercent, na.rm = TRUE),
      #Median = median(R_tongue_protraction_min_CyclePercent, na.rm = TRUE),
      #Min = min(R_tongue_protraction_min_CyclePercent, na.rm = TRUE),
      #Max = max(R_tongue_protraction_min_CyclePercent, na.rm = TRUE))
```
      
```{r subset data for polygon area and run models}
    # response variables- polygon area, body spread, body angle
    # fixed effects - grade(?)
    # speed as continuous covariate
      
      #response variable ~ time + speed + (1 | individual)
      #above is basic model and run with all variations and compare AIC
      #to select model
      # time is categorical predictor (pre v post)
      # speed is continuous predictor (use avg speed + try pre avg speed)
      # also test if effect of time depends on speed (response ~ time * speed)
## subset data_long to get each response variables in appropriate structure to run models
  #1. polygon area
    areas <- data_long %>%filter(variable %in% c("area_fa",
                                                    "area_ahead1",
                                                    "area_ahead2",
                                                    "area_ahead3",
                                                    "area_behind1",
                                                    "area_behind2",
                                                    "area_behind3"))
    # set individual in each data frame as characters so can join data frames
    areas$individual <- as.character(areas$individual)
    pre_speed$individual <- as.character(pre_speed$individual)

    #remove time from pre speed
    pre_speed <- pre_speed %>%
    select(-time)
    
    # add pre_speed as column to areas data frame
    areas_formatted <- areas %>%
      left_join(pre_speed, by = c("date", "mocap_csv_name", "block_number", "individual", "trial", "grade"))
    
    # clean up formatted data frame to consolidate columns and values so in format model expects
    area_data <- areas_formatted %>%
      mutate(area_value = value.x,
             speed = value.y,
             area_type = variable.x,)
    
    #remove duplicate columns from previous step
    area_data <- area_data %>%
      select(-value.x, -value.y, -variable.x, -variable.y)
    
    #set variable as factor
    area_data$area_type <- as.factor(area_data$area_type)

 

## run a general linear mixed model with time and area_type and interaction as fixed effects
    #speed as covariate
    #individual as random effect
    
    #first, set reference levels for model this is what all other levels will be compared to in model
    area_data$time <- relevel(area_data$time, ref = "pre")
    area_data$area_type <- relevel(area_data$area_type, ref = "area_fa")
    
    ## run model 
    time_speed_model <- lmer(area_value ~ time * area_type + speed + (1 | individual),
                         data = area_data)
    summary(time_speed_model)
    
    ## polygon area values in area_fa are significantly higher at post compared with pre time
    ## smaller increases for area_ahead
    ## behind regions show decreases in polygon area over time (esp behind2 and behind3)
    ## speed covariate is significant - faster speed associated with large area values independent of region        and time; speed is strong predictor of area_value
    ##increases from pre to post
      #strongest in FA
      #also present in ahead2 and ahead3 - probaby due to snake moving forward?
    ##decreased from pre to post
      #strongest in behind2
      #moderate in behind3
      #slight decrease in behind1
    ##minimal change in ahead1
    
# calculate Cohen's d to evaluate effect size (0.2 = small, 0.5 = medium, 0.8 = large)
    eff_size(emmeans(time_speed_model, ~ time | area_type),
         sigma = sigma(time_speed_model),
         edf = df.residual(time_speed_model))
    ##effect sizes for pre-post changes vary across spatial chunks
      # large effects (d =0.94, 0.96) in fa and behind2
      # medium effects (d=0.52, 0.47, 0.42) in behind3, ahead2, and ahead3
      # uncertain/small effects in ahead1, behind1 (CI includes 0 unlike all above)
    
      # think we have evidence of increase in total body slide (polygon area) because
        #1. significant increase in polygon area at post for FA chunk
        #2. effect size for this is large 
        
    
    # plot
      # make predicted values from model into data frame
      emm_time_speed <- emmeans(time_speed_model, ~ time * area_type + speed)
      emm_time_speed_df <- as.data.frame(emm_time_speed)
    
      # create plot with area_type
      ggplot(emm_time_speed_df, aes(x = time, y = emmean, color = area_type, group = area_type)) +
        geom_line(size = 1.2) +
        geom_point(size = 3) +
        geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL), width = 0.1) +
        labs(x = "Time", y = "Estimated Mean Value",
            title = "Time × Area_Type + Speed (Mixed Model)") +
        theme_minimal()
      
      # create plot with speed
      # get predicted values from model over grid of speed values
      emm_time_speed_speedplot <- emmeans(
      time_speed_model,
      ~ speed | time * area_type,
      at = list(speed = seq(
        min(area_data$speed, na.rm = TRUE),
        max(area_data$speed, na.rm = TRUE),
        length.out = 50)))
      
      emm_time_speed_speedplot_df <- as.data.frame(emm_time_speed_speedplot)
      
      # plot using speed (continuous) as x
      ggplot(emm_time_speed_speedplot_df,
        aes(x = speed, y = emmean, color = time)) +
        geom_line(size = 1.2) +
        geom_ribbon(
          aes(ymin = lower.CL, ymax = upper.CL, fill = time),
          alpha = 0.2,
          color = NA
        ) +
        facet_wrap(~ area_type) +
        labs(
          x = "Speed",
          y = "Estimated Mean Area Value",
          title = "Predicted Area Values Across Speed",
          color = "Time",
          fill = "Time") +
        theme_minimal()
      
      
## need to create table that organizes the model output and effect sizes and AIC?
      
      
```
``` {r subset data for body angle spread and run models}

  # response variables- polygon area, body spread, body angle
    # speed as continuous covariate
      
      #response variable ~ time + speed + (1 | individual)
      #above is basic model and run with all variations and compare AIC
      #to select model
      # time is categorical predictor (pre v post)
      # speed is continuous predictor (use pre avg speed)
      # also test if effect of time depends on speed (response ~ time * speed)
## subset data_long to get each response variables in appropriate structure to run models
  #2. body angle spread
    spreads <- data_long %>%filter(variable %in% c("avg_body_angle_spread_fa",
                                                    "avg_body_angle_spread_ahead1",
                                                    "avg_body_angle_spread_ahead2",
                                                    "avg_body_angle_spread_ahead3",
                                                    "avg_body_angle_spread_behind1",
                                                    "avg_body_angle_spread_behind2",
                                                    "avg_body_angle_spread_behind3"))
    # set individual in each data frame as characters so can join data frames
    spreads$individual <- as.character(spreads$individual)
    pre_speed$individual <- as.character(pre_speed$individual)

    
    # add pre_speed as column to areas data frame
    spreads_formatted <- spreads %>%
      left_join(pre_speed, by = c("date", "mocap_csv_name", "block_number", "individual", "trial", "grade"))
    
    # clean up formatted data frame to consolidate columns and values so in format model expects
    spread_data <- spreads_formatted %>%
      mutate(spread_value = value.x,
             speed = value.y,
             spread_type = variable.x,)
    
    #remove duplicate columns from previous step
    spread_data <- spread_data %>%
      select(-value.x, -value.y, -variable.x, -variable.y)
    
    #set variable as factor
    spread_data$spread_type <- as.factor(spread_data$spread_type)

 

## run a general linear mixed model with time and area_type and interaction as fixed effects
    #speed as covariate
    #individual as random effect
    
    #first, set reference levels for model this is what all other levels will be compared to in model
    spread_data$time <- relevel(spread_data$time, ref = "pre")
    spread_data$spread_type <- relevel(spread_data$spread_type, ref = "avg_body_angle_spread_fa")
    
    ## run model 
    spread_time_speed_model <- lmer(spread_value ~ time * spread_type + speed + (1 | individual),
                         data = spread_data)
    summary(spread_time_speed_model)
    
  
    
# calculate Cohen's d to evaluate effect size (0.2 = small, 0.5 = medium, 0.8 = large)
    eff_size(emmeans(spread_time_speed_model, ~ time | area_type),
         sigma = sigma(spread_time_speed_model),
         edf = df.residual(spread_time_speed_model))
  
        
    
    # plot
      # make predicted values from model into data frame
      emm_spread_time_speed <- emmeans(spread_time_speed_model, ~ time * area_type + speed)
      emm_spread_time_speed_df <- as.data.frame(emm_spread_time_speed)
    
      # create plot with area_type
      ggplot(emm_spread_time_speed_df, aes(x = time, y = emmean, color = area_type, group = area_type)) +
        geom_line(size = 1.2) +
        geom_point(size = 3) +
        geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL), width = 0.1) +
        labs(x = "Time", y = "Estimated Mean Spread Value",
            title = "Time × Area_Type + Speed (Mixed Model)") +
        theme_minimal()
      
      # create plot with speed
      # get predicted values from model over grid of speed values
      emm_spread_time_speed_speedplot <- emmeans(
      spread_time_speed_model,
      ~ speed | time * area_type,
      at = list(speed = seq(
        min(spread_data$speed, na.rm = TRUE),
        max(spread_data$speed, na.rm = TRUE),
        length.out = 50)))
      
      emm_spread_time_speed_speedplot_df <- as.data.frame(emm_spread_time_speed_speedplot)
      
      # plot using speed (continuous) as x
      ggplot(emm_spread_time_speed_speedplot_df,
        aes(x = speed, y = emmean, color = time)) +
        geom_line(size = 1.2) +
        geom_ribbon(
          aes(ymin = lower.CL, ymax = upper.CL, fill = time),
          alpha = 0.2,
          color = NA
        ) +
        facet_wrap(~ area_type) +
        labs(
          x = "Speed",
          y = "Estimated Mean Spread Value",
          title = "Predicted Spread Values Across Speed",
          color = "Time",
          fill = "Time") +
        theme_minimal()
      
      
## need to create table that organizes the model output and effect sizes and AIC?


```

```{ r subset data for body angle and run models}
  # response variables- polygon area, body spread, body angle
    # speed as continuous covariate
      
      #response variable ~ time + speed + (1 | individual)
      #above is basic model and run with all variations and compare AIC
      #to select model
      # time is categorical predictor (pre v post)
      # speed is continuous predictor (use pre avg speed)
      # also test if effect of time depends on speed (response ~ time * speed)
## subset data_long to get each response variables in appropriate structure to run models
  #3. body angle spread
    body_angle <- data_long %>%filter(variable %in% c("avg_body_angle_fa",
                                                    "avg_body_angle_ahead1",
                                                    "avg_body_angle_ahead2",
                                                    "avg_body_angle_ahead3",
                                                    "avg_body_angle_behind1",
                                                    "avg_body_angle_behind2",
                                                    "avg_body_angle__behind3"))
    # set individual in each data frame as characters so can join data frames
    body_angle$individual <- as.character(body_angle$individual)
    pre_speed$individual <- as.character(pre_speed$individual)

    
    # add pre_speed as column to areas data frame
    spreads_formatted <- spreads %>%
      left_join(pre_speed, by = c("date", "mocap_csv_name", "block_number", "individual", "trial", "grade"))
    
    # clean up formatted data frame to consolidate columns and values so in format model expects
    spread_data <- spreads_formatted %>%
      mutate(spread_value = value.x,
             speed = value.y,
             spread_type = variable.x,)
    
    #remove duplicate columns from previous step
    spread_data <- spread_data %>%
      select(-value.x, -value.y, -variable.x, -variable.y)
    
    #set variable as factor
    spread_data$spread_type <- as.factor(spread_data$spread_type)

 

## run a general linear mixed model with time and area_type and interaction as fixed effects
    #speed as covariate
    #individual as random effect
    
    #first, set reference levels for model this is what all other levels will be compared to in model
    spread_data$time <- relevel(spread_data$time, ref = "pre")
    spread_data$spread_type <- relevel(spread_data$spread_type, ref = "avg_body_angle_spread_fa")
    
    ## run model 
    spread_time_speed_model <- lmer(spread_value ~ time * spread_type + speed + (1 | individual),
                         data = spread_data)
    summary(spread_time_speed_model)
    
  
    
# calculate Cohen's d to evaluate effect size (0.2 = small, 0.5 = medium, 0.8 = large)
    eff_size(emmeans(spread_time_speed_model, ~ time | area_type),
         sigma = sigma(spread_time_speed_model),
         edf = df.residual(spread_time_speed_model))
  
        
    
    # plot
      # make predicted values from model into data frame
      emm_spread_time_speed <- emmeans(spread_time_speed_model, ~ time * area_type + speed)
      emm_spread_time_speed_df <- as.data.frame(emm_spread_time_speed)
    
      # create plot with area_type
      ggplot(emm_spread_time_speed_df, aes(x = time, y = emmean, color = area_type, group = area_type)) +
        geom_line(size = 1.2) +
        geom_point(size = 3) +
        geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL), width = 0.1) +
        labs(x = "Time", y = "Estimated Mean Spread Value",
            title = "Time × Area_Type + Speed (Mixed Model)") +
        theme_minimal()
      
      # create plot with speed
      # get predicted values from model over grid of speed values
      emm_spread_time_speed_speedplot <- emmeans(
      spread_time_speed_model,
      ~ speed | time * area_type,
      at = list(speed = seq(
        min(spread_data$speed, na.rm = TRUE),
        max(spread_data$speed, na.rm = TRUE),
        length.out = 50)))
      
      emm_spread_time_speed_speedplot_df <- as.data.frame(emm_spread_time_speed_speedplot)
      
      # plot using speed (continuous) as x
      ggplot(emm_spread_time_speed_speedplot_df,
        aes(x = speed, y = emmean, color = time)) +
        geom_line(size = 1.2) +
        geom_ribbon(
          aes(ymin = lower.CL, ymax = upper.CL, fill = time),
          alpha = 0.2,
          color = NA
        ) +
        facet_wrap(~ area_type) +
        labs(
          x = "Speed",
          y = "Estimated Mean Spread Value",
          title = "Predicted Spread Values Across Speed",
          color = "Time",
          fill = "Time") +
        theme_minimal()
      
      
## need to create table that organizes the model output and effect sizes and AIC?

```

```{r junk code and notes to me}
## note to me:
      # have template of analysis approach - repeat with other variables and include speed
      # run lmer models and then use AIC() or summary(model) to get model comparison metric
      # as a continuous covariate?? - yes
      # want to create tables with model output eventually

#time_speed_model <- lmer(value ~ time * variable + (1 | individual), data = area_formatted)

 #2. body spread
    #body_spread <- data_long[
      #data_long$variable %in% c(
        #"avg_body_angle_spread_fa",
        #"avg_body_angle_spread_ahead1",
        #"avg_body_angle_spread_ahead2",
        #"avg_body_angle_spread_ahead3",
        #"avg_body_angle_spread_behind1",
        #"avg_body_angle_spread_behind2",
        #"avg_body_angle_spread_behind3"
      #) |
      #(
        #data_long$time == "pre" &
        #data_long$variable == "avg_speed"),]
    
  #3. body angle
    #body_angle <- data_long[
      #data_long$variable %in% c(
        #"avg_body_angle_fa",
        #"avg_body_angle_ahead1",
        #"avg_body_angle_ahead2",
        #"avg_body_angle_ahead3",
        #"avg_body_angle_behind1",
        #"avg_body_angle_behind2",
        #"avg_body_angle_behind3"
      #) |
      #(
        #data_long$time == "pre" &
        #data_long$variable == "avg_speed"),]
    
## model sandbox 
## run a gamma general linear mixed model 
  #model <- glmer(value ~ variable * time * grade +
                 #(1 | individual),
                 #data = data_long,
                 #family = Gamma(link = "log"))
  #summary(model)
  
  # above model is OK for all variables except avg body angle and speed change which   # have uniform and normal distributions, respectively


## does average pre speed differ between grade A and B?
  # subset data for model
  #pre_speed_data <- data_long[data_long$variable == "avg_speed" & 
                                #data_long$time =="pre",]
 
   # run general linear model on pre speed + deal with repeated measures
    #grade_model <- glm(value ~ grade, data = pre_data, family = gaussian())
    #summary(grade_model)
      
    #model <- lmer(value ~ grade + (1 | individual), data = pre_speed_data)
    #summary(model)
  
    # does the effect of pre v post change depending on speed?
    # predictors = variable, time, grade, speed (as continuous covariate)
    # outcome = value (all output variables)
    #model <- lmer(value ~ variable * time * grade + speed * time + 
              #(1 | individual),
              #data = data_long)

```


